# Generated by Django 3.0.3 on 2020-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200529_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
