# Generated by Django 3.0.3 on 2020-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_degree_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
